# Generated by Django 4.2.20 on 2025-04-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_checker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzedImage',
        ),
    ]
